apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: <YOUR NODE GROUP ARN>
      username: system:node:{{EC2PrivateDNSName}}
      groups:
      - system:bootstrappers
      - system:nodes
    - rolearn: <DEVOPS ROLE ARN>
      username: devops
      groups:
        - system:masters
    - rolearn: <DEVELOPER ROLE ARN>
      username: developer
      groups:
        - aws:iam-developer-role
