---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-imds2
  namespace: preprod
spec:
  selector:
    matchLabels:
      app: nginx-imds2
  template:
    metadata:
      labels:
        app: nginx-imds2
    spec:
      nodeSelector:
        facam/node: imds-h2
      containers:
      - name: nginx-imds2
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 512Mi
