apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: imds-h2
spec:
  requirements:
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ["t3.medium"]
  providerRef:
    name: imds-h2
  ttlSecondsAfterEmpty: 30
  labels:
    facam/node: imds-h2
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: imds-h2
spec:
  instanceProfile: "karpenter-node"
  subnetSelector:
    Name: "private-ap-*"
    kubernetes.io/cluster/facam-ts-handson: "shared"
  securityGroupSelector:
    Owner: "karpenter/facam-ts-handson"
    kubernetes.io/cluster/facam-ts-handson: "shared"
  tags:
    Owner: "karpenter/facam-ts-handson"
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
