apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: foo
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: foo
  targetCPUUtilizationPercentage: 20
