---
apiVersion: v1
kind: Pod
metadata:
  name: foo
  namespace: preprod
spec:
  containers:
  - name: foo
    image: alpine/curl:3.14
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi
    command: ['sleep', '86400']
