---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cpu
  namespace: preprod
spec:
  selector:
    matchLabels:
      app: nginx-cpu
  template:
    metadata:
      labels:
        app: nginx-cpu
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
