---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-a
  namespace: preprod
spec:
  selector:
    matchLabels:
      app: nginx-a
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-a
    spec:
      nodeSelector:
        facam/node: common
      containers:
      - name: nginx-a
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-a
  namespace: preprod
spec:
  selector:
    app: nginx-a
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
